pipeline:
  publish:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/znc
    tags:
    - latest
    - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    when:
      branch: master

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: kubernetes
    when:
      status: [success, failure]
